apiVersion: v1
kind: Pod
metadata:
  name: live-config-demo
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sh
      - -c
      - |
        while true
        do
          cat /config/message
          sleep 5
        done

    volumeMounts:
      - name: config
        mountPath: /config

  volumes:
    - name: config
      configMap:
        name: live-config